defaults:
  -
    scope:
      path: ""
    values:
      layout: "blog"

#pagination
paginate: 5
paginate_path: "/blogs/page:num/"
excerpt_separator: "<!--more-->"
permalink: none

# Handling Reading
include:      [".htaccess"]
exclude:      ["Gemfile.lock","Gemfile"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Custom vars
author: "Ibnu Abas"
